spring:
  profiles:
    active:
     - prod

guru:
  username: ymluser
  password: ymlpassword
  jdburl: ymlurl

---
spring:
  profiles: prod
guru:
  username: ymlproduser
  password: ymlprodpassword
  jdburl: ymlprodurl
